### ISSUE TITLE
Bug-Report on Spigot 1.20.4

### ISSUE THREAD

**Issue by Robin-Arnhardt** [kiranhart/Auction-House#105]
Hello, i get this Console Errors on Start the Server / write a command: https://prnt.sc/z-qF5tITe-iR | https://prnt.sc/MPrK6ojmNWIj

Server Version: https://prnt.sc/8c4ARroeaKfY

I use the newest AH Version (2.132.1)

I hope you can fix it. 

Thanks

**Comment by kiranhart** [comment]
1.21.4 isn't supported yet. Have to wait on nbtapi
