### ISSUE TITLE
Item vanishes when chaning price

### ISSUE THREAD

**Issue by DuneSciFye** [kiranhart/Auction-House#16]
**Describe the bug**
When putting an item in the gui menu to list it, and changing the price by clicking the sunflower, when the menu comes back the item is no longer there.

**To Reproduce**

- Describe how to reproduce this bug: EX.

1. Open the main menu
2. Click list item
3. Put any item in
4. Change price

**Expected behavior**
Item doesn't dissapear

**Screenshots**
https://streamable.com/1k5fta

**Server Information (please complete the following information):**

Previous: git-Purpur-1765 (MC: 1.19.2)
AuctionHouse version 2.76.0

**Comment by kiranhart** [comment]
Running old version

**Comment by DuneSciFye** [comment]
Updated to latest, after clicking the set price button no commands work. https://streamable.com/8a89us
