### ISSUE TITLE
Unlimited Offers - Bug reducing the amount of items

### ISSUE THREAD

**Issue by BartosB13** [kiranhart/Auction-House#24]
**Describe the bug**
Hello!

This error is very problematic and has been happening regularly for several weeks. Only recently has it been confirmed what is going on. I noticed that a offer, the number of items decreases by 2^x (2,4,8,16 etc.) Sometimes offers change several times gradually. I don't know what exactly causes it.

**To Reproduce**

1. List the item with the /ah sell command using the -i argument
2. Players regularly buy an offer
3. After some time, it turns out that the offer has too few items.

**Examples:**

- Earlier there were fireworks power 3 x16 - Then after some time their number decreased to 2
- Bread x64 - After some time, its number in the offer decreased to 2
- Latest example: Gunpowder x64 decreased to 1

**Screenshots**

![image](https://user-images.githubusercontent.com/89303317/205989016-10f1e37d-ef0d-415c-8baa-1aaf568567bc.png)

**Server Information (please complete the following information):**

- paper 1.19.2 301
- Plugin Version 2.80.2

**Comment by BartosB13** [comment]
Redstone Lamps - The offer has broken, from 64 to 4:

![image](https://user-images.githubusercontent.com/89303317/206013893-62881a87-676a-4ace-a63f-eb4a4a9370f3.png)

**Comment by kiranhart** [comment]
So just to confirm, the infinite listing items are randomly losing their initial stack qty right?

**Comment by BartosB13** [comment]
Yes. But I don't know what it comes from

**Comment by BartosB13** [comment]
New, gunpowder 64 -> 7

![image](https://user-images.githubusercontent.com/89303317/206437897-29e47f47-22ea-4792-8191-b0cd9b5badaa.png)

**Comment by kiranhart** [comment]
Do you have the option to let players purchase a specific qty from that non bid items enabled?

**Comment by BartosB13** [comment]
For these items I only use the -i argument (I don't use -p)

**Comment by BartosB13** [comment]
How is the work on solving this problem going? We use random weekly offers on the server. They are added on the market using the -i function. This error causes these offers to change their values, which is very problematic.

**Comment by kiranhart** [comment]
Haven't had any luck on this unfortunately, finishing up markets 2.0 and I'll get back to bug reports

**Comment by BartosB13** [comment]
What is the situation? I've seen that there have been a lot of different fixes lately and there are fewer topics on github

**Comment by kiranhart** [comment]
Yea I was able to finally re-create it, so have a general idea on whats causing it now

**Comment by BartosB13** [comment]
latest version plugin
![bug ah](https://user-images.githubusercontent.com/89303317/224581767-4f852536-45cb-40c9-a0ae-8e62d313eb68.png)

**Comment by BartosB13** [comment]
The cause of the error has been found! (Or one of the reasons?)

Now it may be easy to fix. I'm already writing what's going on.

How to repeat the error (Example):

1. Listing an offer for 64 blocks of sand (Seller + unlimited -i)
2. Have 7 sand blocks in your inventory (Buyer)
3. Purchase an unlimited offer of 64 blocks of sand (Buyer)
4. From now on, the offer of unlimited sand blocks will have 7 sand blocks instead of 64.

More or less such a mechanism causes an error. But I don't know if this is the only reason for this error.

**Comment by kiranhart** [comment]
@BartosB13 Hey, any confirmation on whether the latest version has resolved this?

**Comment by kiranhart** [comment]
Re-Open if it still exists
