### ISSUE TITLE
Blocked Items does not work

### ISSUE THREAD

**Issue by FinnChildress** [kiranhart/Auction-House#33]
**Describe the bug**
It is not possible to block certain items from being sold. The item blacklists seem to have no effect

**To Reproduce**

1. Install latest version with default config
2. View in default plugin config that ENDER_CHEST should be denied and "fuck" is not allowed as the item name
3. Sell an EnderChest that is named "fuck" on the auctionhouse using /ah sell

**Expected behavior**
Unable to sell an enderchest or an item named "fuck". And certainly not an item that matches both blacklists

**Screenshots**
![image](https://user-images.githubusercontent.com/33529688/208621882-c224d1eb-10fd-4ad8-bb85-c0094fb0625a.png)

**Server Information (please complete the following information):**

- Provide the server version 1.17.1
- Provide the server jar (ex. paper/spigot) Purpur
- Plugin Version 2.81.0

**Additional context**
I have tried adding other things to the blacklists and nothing has worked.

**Comment by kiranhart** [comment]
Ah this happens when you use the gui right?

**Comment by FinnChildress** [comment]
Yes
