### ISSUE TITLE
Offline Payments

### ISSUE THREAD

**Issue by RamonBlissenbach** [kiranhart/Auction-House#37]
If a player buys something from a player who is offline, the player does not get the money.

![image](https://user-images.githubusercontent.com/84371607/211926349-4c6012f6-4629-48d8-9e25-14925b6da555.png)
![image](https://user-images.githubusercontent.com/84371607/211926364-a16c4286-e97a-4d3b-b004-e14d71d45620.png)

**Comment by kiranhart** [comment]
So I just tested this and it worked fine on my end.

**Comment by Ayont** [comment]
Its working for me not too why?

**Comment by RamonBlissenbach** [comment]
> So I just tested this and it worked fine on my end.

It doesn't work for me.
