### ISSUE TITLE
Bug in the item bundles interface

### ISSUE THREAD

**Issue by Evalutik** [kiranhart/Auction-House#44]
1) When players form a bundle to put it up for auction, there are 4 rows of 9 slots available in the menu where things can be put in. After the bundle is put up for auction, the top row is not available during the inspection of the bundle, (It replaced by placeholder slots). If the bundle was completely full, then there will still be only 3 rows of titems on the first page, and the fourth will be on the second page. This can be very confusing.

**To Reproduce 1**

1. type just /ah sell
2. any type
3. go to bundle mod
4. fill all 36 slots (we see that the top row **is available**)
5. next
6. confirm placement
7. go to /ah
8. find our bundle
9. shift+right click to inspect
10. we see that the top row **is not available**

**Expected behavior 1**

We should see that the top row **is available**

**Screenshots for 1**

Forming view:
![image](https://user-images.githubusercontent.com/126126362/226170447-1a0b4dd6-3e11-4333-a173-da023e9c0150.png)
Inspection view:
![image](https://user-images.githubusercontent.com/126126362/226170356-a21e0881-5b21-44eb-b7b1-cd9e66ec89cd.png)

_2) In addition, once a bundle is put up for auction, items in the view menu are out of order if they were scattered around the bunch. (For example, I put 2 items in the 3rd and 15th slots, when I form a bundle, then during the inspection of the bundle, these items will lie in the first and second slots)_

_**To Reproduce 2**

1. type just /ah sell
2. any type
3. go to bundle mod
4. fill any two non-adjacent slots and remember the order
5. next
6. confirm placement
7. go to /ah
8. find our bundle
9. shift+right click to inspect
10. we see that order and arrangement of items are not preserved

**Expected behavior 2**

The order and arrangement of items should have been preserved_

**Screenshots for 2**

Forming view:
![image](https://user-images.githubusercontent.com/126126362/226170562-021829f1-152f-461c-b4ee-18206dabb60b.png)
Inspection view:
![image](https://user-images.githubusercontent.com/126126362/226170589-0d3877e9-6345-42e9-a30e-2f41ad330716.png)

**Server Information**

- Provide the server version: PurPur 1.19.3
- Plugin Version: Auction House — v2.89.0

**Comment by kiranhart** [comment]
Not a bug, this is an enhancement.

The placement of items doesn't matter due to how it's designed to be stored.
