### ISSUE TITLE
Get Money and item on bid cancel

### ISSUE THREAD

**Issue by Mithranduil** [kiranhart/Auction-House#46]
1. Open the main menu
2. Sell Item for likely 1$ as an bid item
3. bid with an other account on the item, for like 2$, so i get 2$ as an bid on my item
4. now i cancel the bid and get item and the money that is bid on that item

Paper-376 - 1.19.3
Auctionhouse version: 2.91.0

**Comment by kiranhart** [comment]
Resolved in #ab973ab
