### ISSUE TITLE
auctionhouse.transactions.viewall dont do anything

### ISSUE THREAD

**Issue by Evalutik** [kiranhart/Auction-House#66]
it seems like auctionhouse.transactions.viewall dont do anything, I can view "all transaction" menu in the /ah transactions as well as personal transactions, just have auctionhouse.cmd.transactions and, even auctionhouse.transactions.viewall = false

**To Reproduce**

1 auctionhouse.cmd.transactions and  auctionhouse.transactions.viewall = false to the player
2 go to /ah transactions
3 u can still view other player's transactions

I would like the personal transactions menu icon to also be centered in the /ah transactions menu so that the symmetry is preserved when the player is not allowed to view the general transactions of all players, but only the view of personal transactions is available. Or better yet, the /ah tramsactions menu will immediately jump to the personal transactions menu if the player does not have rights to view the server's general transactions

**Comment by kiranhart** [comment]
Turning on the setting: "restrict viewing all transactions" should achieve this functionality.
