### ISSUE TITLE
Ender crystals duplicate

### ISSUE THREAD

**Issue by JrRequeim** [kiranhart/Auction-House#70]
**Describe the bug**
Ender crystal duplicate

**To Reproduce**

Fast enter /ah sell 321312 and put crystal.

**Expected behavior**
Cant duplitacate items

**Screenshots**

**Server Information (please complete the following information):**

Purpur 1.20.1 build 2033,  plugin ver 2.100.3

**Additional context**
same issue with keys from excellent crates.

https://github.com/kiranhart/Auction-House/assets/142319886/d73d6022-5a34-4754-8205-716ecaf06cfe

**Comment by kiranhart** [comment]
Was resolved in 2.100.4
