### ISSUE TITLE
Full Inventory Money Drain

### ISSUE THREAD

**Issue by HalfloveJAR** [kiranhart/Auction-House#75]
**Describe the bug**
if you have the winning bid on an ah item and ur inv is full when the timer runs out or the person accepts the bid it will keep taking your money until you create space in your inv.

**To Reproduce**

1. Player 1 puts item up for auction
2. Player 2 bids on item
3. Player 1 accepts auction OR Player 2 wins auction normally
4. If Player 2 has a full inventory the bug will occur

**Expected behavior**
Player 2 should pay the bill once, receive the item(s) and complete.

**Screenshots**
![image](https://github.com/kiranhart/Auction-House/assets/29326375/1bfbfa96-8b77-4caf-b4e7-ebb3f322a7bc)

**Server Information (please complete the following information):**

- Minecraft 1.20.1 
- Purpur build 2060
- Plugin Version 2.103.1

**Additional context**
When the bug occurs it will continue taking your money until you make space in your inventory or run out of money.

**Comment by kiranhart** [comment]
Can you try enabling "synchronize item add" in the config and see if that resolves the issue?

**Comment by HalfloveJAR** [comment]
Doing that drops the item on the ground instead, fixing the issue 👍
