### ISSUE TITLE
full inventory and auction bid wins

### ISSUE THREAD

**Issue by sennby** [kiranhart/Auction-House#85]
![image](https://github.com/kiranhart/Auction-House/assets/138246331/913226ef-59fd-4407-96a3-564f67d30062)

This player won an auction but his inventory was full. it took his money 3x and he got no item.

1.20.4
latest AH

**Comment by kiranhart** [comment]
try enabling "synchronize item add" in the config

**Comment by sennby** [comment]
I already do
