### ISSUE TITLE
Items disappearing Bug

### ISSUE THREAD

**Issue by Zockerhd01** [kiranhart/Auction-House#90]
**Describe the bug**
When you have the /ah sell price confirm menu on, it will delete your item if you get kicked for wifi while being in the confirm menu.

**To Reproduce**

- Describe how to reproduce this bug: EX.

1. /ah sell price
2. Disconnect inside the confirm menu
3. Item is gone when rejoining

**Expected behavior**
You should be able to get the items back

**Screenshots**
![image](https://github.com/kiranhart/Auction-House/assets/100472010/7cc58c36-365d-4c51-a329-5b1b0b93dd10)

**Comment by Bani4kaa** [comment]
Hey! I got the same bug with my players on my network today! I hope this get's fixed really soon!
