### ISSUE TITLE
problem with items disappearing

### ISSUE THREAD

**Issue by lol1d1** [kiranhart/Auction-House#98]
When I click the refresh item list button, items can disappear. The same thing happens when you select a category and then reset it.

https://github.com/user-attachments/assets/e10fc5fd-1586-4ead-acab-515ebea9fdd8

**Comment by lol1d1** [comment]
the console displays the message "Cancelled updating task in menu"

**Comment by lol1d1** [comment]
![image](https://github.com/user-attachments/assets/d20ec4c5-5261-40ac-a6d8-17cd41e549de)

**Comment by kiranhart** [comment]
Should be resolved now, that console message is just a debug message nothing to worry about. If the issue is still a thing just re-open the issue
